service:
  name: cloudwatch-sns-slack-notifier

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: prod

functions:
  notify-slack:
    handler: handler.handler
